Repository jgarzik/gdbm-native-rs, pull requests merged in 2024-10, with the labels that each got.

#71 API-Remove init fix
  src/bucket.rs
  src/lib.rs
Labels: bug

#75 Cargo.toml: move serde to dev-deps
  Cargo.toml
Labels: cleanup

#80 Update README.md: move status progress to GH issues
  README.md
Labels: documentation

#81 delete Notes. outdated.
  Notes.md
Labels: documentation, cleanup

#87 enhancement: cache eviction
  src/bucket.rs
  src/lib.rs
  tests/common/mod.rs
  tests/iterate.rs
  tests/open.rs
Labels: enhancement
